{
  "comments": [
    {
      "key": {
        "uuid": "4e38dfd0_5781935c",
        "filename": "common/py_utils/py_utils/compatibility/__init__.py",
        "patchSetId": 9
      },
      "lineNbr": 59,
      "author": {
        "id": 1181690
      },
      "writtenOn": "2017-10-25T16:20:56Z",
      "side": 1,
      "message": "nit: s/devil/py_utils/",
      "revId": "2c01cd8abce604534758d987d38bb9fe9b2db03f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}