{
  "comments": [
    {
      "key": {
        "uuid": "db97ce73_7fafa640",
        "filename": "common/py_utils/py_utils/exc_util.py",
        "patchSetId": 1
      },
      "lineNbr": 88,
      "author": {
        "id": 1123010
      },
      "writtenOn": "2019-05-14T14:48:31Z",
      "side": 1,
      "message": "I\u0027m including this here as an example of another thing I tried but turned out to be more awkward and harder to use correctly. Planning to remove before committing this change.",
      "revId": "b100a35eddac225641dda8f3fdf2541fa3717fce",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "11fef844_431f5e59",
        "filename": "common/py_utils/py_utils/exc_util.py",
        "patchSetId": 1
      },
      "lineNbr": 129,
      "author": {
        "id": 1123010
      },
      "writtenOn": "2019-05-14T14:48:31Z",
      "side": 1,
      "message": "The fact that a regular try-except-finally block does not work, and this monster is needed instead, was the main reason for me to abandon this approach.",
      "revId": "b100a35eddac225641dda8f3fdf2541fa3717fce",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}