{
  "comments": [
    {
      "key": {
        "uuid": "44ea8802_b47ec71b",
        "filename": "devil/devil/android/device_utils.py",
        "patchSetId": 1
      },
      "lineNbr": 685,
      "author": {
        "id": 1181690
      },
      "writtenOn": "2019-04-05T17:14:12Z",
      "side": 1,
      "message": "Do we know anything about these \"rare cases\"? Do we know why pm path would fail to find the package while pm dump would succeed in doing so?",
      "revId": "c3b0670283819ac017b2565c10100e2edf4e34dd",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}