{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "945c8beb_c6e74ffd",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1373330
      },
      "writtenOn": "2022-12-02T22:03:59Z",
      "side": 1,
      "message": "PTAL.\n(I\u0027m thinking whether we should still return u\u0027\u0027 if PY2. We used a ijson from third_party/, and the compat.py is implemented differently.)",
      "revId": "f1fad85b9eb50c64b2d60518a63474815db6bcc2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "f6c32be3_9fa0a0b9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1181219
      },
      "writtenOn": "2022-12-02T22:17:29Z",
      "side": 1,
      "message": "When the buffer isn\u0027t empty, PY2 would return normal string, so it was inconsistent to return u\u0027\u0027 when buffer is empty. But I suppose it worked before.",
      "parentUuid": "945c8beb_c6e74ffd",
      "revId": "f1fad85b9eb50c64b2d60518a63474815db6bcc2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "3f222871_3a25460f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1181219
      },
      "writtenOn": "2022-12-02T22:17:29Z",
      "side": 1,
      "message": "LGTM",
      "revId": "f1fad85b9eb50c64b2d60518a63474815db6bcc2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "c8762f74_2b138314",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 2
      },
      "lineNbr": 0,
      "author": {
        "id": 1373330
      },
      "writtenOn": "2022-12-02T22:26:16Z",
      "side": 1,
      "message": "I think it worked because running encode on bytes (which is string) in python2 will not throw. In python 3, it throws attribute error.",
      "parentUuid": "f6c32be3_9fa0a0b9",
      "revId": "f1fad85b9eb50c64b2d60518a63474815db6bcc2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}